-- ==================================================
-- TABLE NAME
--   ra_report_exports
--
-- Purpose
--   Immutable operational history of generated report files and downloads.
--
-- Relationships
--   Each export belongs to a saved report and is generated by a user.
--
-- Indexes
--   Report, exporter, export type/date, and download analytics.
--
-- Workflow
--   Generate -> store file -> download repeatedly -> retain for audit.
--
-- Author
--   CBL HSE Database Architecture
--
-- Version
--   1.0.0 | Reporting and Analytics Extension | MySQL 8
-- ==================================================

USE cbl_hse;

CREATE TABLE IF NOT EXISTS ra_report_exports (
    export_id       BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    report_id       BIGINT UNSIGNED NOT NULL,
    exported_by     BIGINT UNSIGNED NOT NULL,
    export_type     ENUM('PDF','Excel','CSV') NOT NULL,
    file_path       VARCHAR(1000) NOT NULL,
    generated_at    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    download_count  INT UNSIGNED NOT NULL DEFAULT 0,
    created_by      BIGINT UNSIGNED NOT NULL,
    updated_by      BIGINT UNSIGNED NOT NULL,
    created_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at      DATETIME(3) NULL,
    PRIMARY KEY (export_id),
    CONSTRAINT fk_ra_export_report FOREIGN KEY (report_id) REFERENCES ra_saved_reports(report_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_ra_export_user FOREIGN KEY (exported_by) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_ra_export_created_by FOREIGN KEY (created_by) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_ra_export_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    INDEX idx_ra_export_report_date (report_id,generated_at),
    INDEX idx_ra_export_user_date (exported_by,generated_at),
    INDEX idx_ra_export_type_date (export_type,generated_at),
    INDEX idx_ra_export_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Report export and download history.';

INSERT INTO ra_report_exports
    (report_id,exported_by,export_type,file_path,generated_at,download_count,created_by,updated_by)
SELECT
    MOD(seq - 1,20) + 1,
    CASE WHEN MOD(seq,3)=0 THEN 4 WHEN MOD(seq,2)=0 THEN 2 ELSE 1 END,
    CASE MOD(seq,3) WHEN 0 THEN 'CSV' WHEN 1 THEN 'PDF' ELSE 'Excel' END,
    CONCAT('reports/2026/',LPAD(seq,4,'0'),'-hse-report.',LOWER(CASE MOD(seq,3) WHEN 0 THEN 'csv' WHEN 1 THEN 'pdf' ELSE 'xlsx' END)),
    DATE_ADD('2026-01-05 08:00:00',INTERVAL seq * 7 DAY),
    MOD(seq,9),
    1,1
FROM (
    SELECT ones.n + tens.n * 10 + 1 AS seq
    FROM (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) ones
    CROSS JOIN (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3) tens
) s
WHERE seq <= 40;

