-- ==================================================
-- TABLE NAME
--   ra_analytics_snapshots
--
-- Purpose
--   Stores daily pre-calculated analytics values for fast executive dashboards.
--
-- Relationships
--   Optionally scoped to existing departments; generated by the reporting job.
--
-- Indexes
--   Snapshot date, module/metric, department, and uniqueness for idempotent loads.
--
-- Workflow
--   ETL calculates -> upserts daily value -> dashboard reads snapshot -> retain history.
--
-- Author
--   CBL HSE Database Architecture
--
-- Version
--   1.0.0 | Reporting and Analytics Extension | MySQL 8
-- ==================================================

USE cbl_hse;

CREATE TABLE IF NOT EXISTS ra_analytics_snapshots (
    snapshot_id     BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    snapshot_date   DATE NOT NULL,
    module_name     VARCHAR(80) NOT NULL,
    department_id   CHAR(36) NULL,
    metric_name     VARCHAR(160) NOT NULL,
    metric_value    DECIMAL(20,4) NOT NULL,
    generated_at    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by      BIGINT UNSIGNED NOT NULL,
    updated_by      BIGINT UNSIGNED NOT NULL,
    created_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at      DATETIME(3) NULL,
    PRIMARY KEY (snapshot_id),
    UNIQUE KEY uq_ra_snapshot_metric (snapshot_date,module_name,department_id,metric_name),
    CONSTRAINT fk_ra_snapshot_department FOREIGN KEY (department_id) REFERENCES departments(department_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_ra_snapshot_created_by FOREIGN KEY (created_by) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_ra_snapshot_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    INDEX idx_ra_snapshot_date_module (snapshot_date,module_name),
    INDEX idx_ra_snapshot_metric (metric_name,snapshot_date),
    INDEX idx_ra_snapshot_department (department_id,snapshot_date),
    INDEX idx_ra_snapshot_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Daily analytics snapshot fact table.';

WITH RECURSIVE calendar AS (
    SELECT DATE('2026-01-01') AS snapshot_date
    UNION ALL
    SELECT snapshot_date + INTERVAL 1 DAY FROM calendar WHERE snapshot_date < '2026-12-31'
)
INSERT INTO ra_analytics_snapshots
    (snapshot_date,module_name,department_id,metric_name,metric_value,generated_at,created_by,updated_by)
SELECT
    snapshot_date,
    'Executive',
    NULL,
    'Leading Indicator Index',
    ROUND(82 + (DAYOFYEAR(snapshot_date) MOD 19) * 0.65,4),
    CONCAT(snapshot_date,' 06:00:00'),
    1,1
FROM calendar;

