-- =============================================================================
-- 15_hazards.sql
-- CBL HSE Management System — Phase 3: Hazard Management Module
-- Table: hazards
--
-- Purpose:
--   The CORE table of the entire HSE Hazard Management module.
--   Stores every hazard report from initial submission to permanent closure.
--   Supports the complete 9-stage hazard lifecycle:
--     Draft → Submitted → Assigned → In Progress → Pending Review
--     → Approved → Closed (or Rejected → Reopened → loop)
--
-- Relationships (this table is the hub):
--   plants            → hazards (one plant → many hazards)
--   departments       → hazards (one department → many hazards)
--   locations         → hazards (one location → many hazards)
--   employees         → hazards.reported_by (reporter)
--   employees         → hazards.responsible_person_id
--   employees         → hazards.reviewer_id
--   employees         → hazards.affected_employee_id
--   contractors       → hazards.contractor_id
--   hazard_categories → hazards.category_id
--   hazard_types      → hazards.hazard_type_id
--   risk_ratings      → hazards.risk_rating_id
--   statuses          → hazards.status_id
--   users             → hazards.created_by / updated_by
--
-- Child tables depending on this:
--   16_hazard_attachments.sql
--   17_hazard_corrective_actions.sql
--   18_hazard_reviews.sql
--   19_hazard_status_history.sql
--   20_hazard_notifications.sql
--
-- Performance Notes:
--   Designed for millions of records. Composite indexes align with common
--   dashboard query patterns (department+date, status+plant, risk+date).
--
-- Depends on: 11, 12, 13, 14, employees, contractors, plants, departments, locations, users
-- Run: SOURCE database/schema/15_hazards.sql;
-- =============================================================================

USE cbl_hse;

-- -----------------------------------------------------------------------------
-- Table Definition
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS hazards (

    -- ─────────────────────────────────────────────────────────────────────────
    -- SECTION 1: Identity
    -- ─────────────────────────────────────────────────────────────────────────

    hazard_id               BIGINT UNSIGNED     NOT NULL AUTO_INCREMENT              COMMENT 'Surrogate PK — integer for fast child table joins.',
    hazard_number           VARCHAR(30)         NOT NULL                             COMMENT 'Human-readable unique reference number. Format: HAZ-{YEAR}-{PLANT_CODE}-{SEQUENCE}. e.g. HAZ-2026-SKR-00001. Generated by application layer.',
    title                   VARCHAR(250)        NOT NULL                             COMMENT 'Short, descriptive title of the hazard. e.g. Exposed live wire near Boiler Area.',

    -- ─────────────────────────────────────────────────────────────────────────
    -- SECTION 2: Location & Scope
    -- ─────────────────────────────────────────────────────────────────────────

    plant_id                CHAR(36)            NOT NULL                             COMMENT 'FK → plants.plant_id — which plant this hazard was observed in.',
    department_id           CHAR(36)            NULL                                 COMMENT 'FK → departments.department_id — department where hazard occurred.',
    location_id             CHAR(36)            NULL                                 COMMENT 'FK → locations.location_id — specific location within the plant.',
    location_detail         VARCHAR(300)        NULL                                 COMMENT 'Free-text additional location detail. e.g. "Near compressor 3, east wall".',

    -- ─────────────────────────────────────────────────────────────────────────
    -- SECTION 3: Classification
    -- ─────────────────────────────────────────────────────────────────────────

    category_id             BIGINT UNSIGNED     NOT NULL                             COMMENT 'FK → hazard_categories.category_id — primary classification of the hazard.',
    hazard_type_id          BIGINT UNSIGNED     NULL                                 COMMENT 'FK → hazard_types.hazard_type_id — type/nature of hazard (Unsafe Act, Unsafe Condition, etc.).',
    risk_rating_id          BIGINT UNSIGNED     NULL                                 COMMENT 'FK → risk_ratings.risk_rating_id — initial risk rating assigned by reporter.',
    revised_risk_rating_id  BIGINT UNSIGNED     NULL                                 COMMENT 'FK → risk_ratings.risk_rating_id — risk rating after HSE review/corrective action.',
    status_id               BIGINT UNSIGNED     NOT NULL                             COMMENT 'FK → statuses.status_id where module_name = ''hazards''. Current lifecycle status.',

    -- ─────────────────────────────────────────────────────────────────────────
    -- SECTION 4: People
    -- ─────────────────────────────────────────────────────────────────────────

    reported_by             CHAR(36)            NOT NULL                             COMMENT 'FK → employees.employee_id — person who observed and reported this hazard.',
    responsible_person_id   CHAR(36)            NULL                                 COMMENT 'FK → employees.employee_id — person responsible for implementing corrective actions.',
    reviewer_id             CHAR(36)            NULL                                 COMMENT 'FK → employees.employee_id — HSE officer assigned to review this hazard.',
    approver_id             CHAR(36)            NULL                                 COMMENT 'FK → employees.employee_id — HSE Administrator who will approve/reject closure.',
    affected_employee_id    CHAR(36)            NULL                                 COMMENT 'FK → employees.employee_id — if a specific employee was directly affected/involved.',
    contractor_id           CHAR(36)            NULL                                 COMMENT 'FK → contractors.contractor_id — if a contractor was involved.',
    area_manager_id         CHAR(36)            NULL                                 COMMENT 'FK → employees.employee_id — department/area manager notified of this hazard.',

    -- ─────────────────────────────────────────────────────────────────────────
    -- SECTION 5: Description
    -- ─────────────────────────────────────────────────────────────────────────

    description             TEXT                NOT NULL                             COMMENT 'Detailed description of the hazard as observed by the reporter.',
    observation             TEXT                NULL                                 COMMENT 'What was specifically observed — the physical condition or act witnessed.',
    immediate_action        TEXT                NULL                                 COMMENT 'Any immediate action taken at the time of reporting to control the hazard.',
    corrective_action_summary TEXT              NULL                                 COMMENT 'Summary of the overall corrective actions plan (populated by HSE/responsible person).',
    recommended_action      TEXT                NULL                                 COMMENT 'Recommendations made by the reporter for long-term prevention.',
    rejection_reason        TEXT                NULL                                 COMMENT 'Reason provided by HSE when the hazard report or closure is rejected.',
    closure_remarks         TEXT                NULL                                 COMMENT 'Final remarks recorded at the time of permanent closure.',

    -- ─────────────────────────────────────────────────────────────────────────
    -- SECTION 6: Dates & Timeline
    -- ─────────────────────────────────────────────────────────────────────────

    date_reported           DATE                NOT NULL                             COMMENT 'The calendar date on which the hazard was observed. Selected from UI date picker.',
    time_reported           TIME                NULL                                 COMMENT 'The time at which the hazard was observed (24h format).',
    reported_datetime       DATETIME(3)         NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Exact timestamp when the record was first submitted to the system.',
    assigned_date           DATETIME(3)         NULL                                 COMMENT 'Timestamp when the hazard was assigned to the responsible person.',
    target_completion_date  DATE                NULL                                 COMMENT 'Target date for completing all corrective actions. Drives overdue calculations.',
    actual_completion_date  DATE                NULL                                 COMMENT 'Date when the responsible person marked all actions complete.',
    review_date             DATETIME(3)         NULL                                 COMMENT 'Date when HSE reviewed the completed hazard.',
    approval_date           DATETIME(3)         NULL                                 COMMENT 'Date when the hazard was approved by HSE Administrator.',
    closure_date            DATETIME(3)         NULL                                 COMMENT 'Date when the hazard was permanently closed.',
    last_reminder_sent      DATETIME(3)         NULL                                 COMMENT 'Timestamp of the last automated reminder notification sent.',

    -- ─────────────────────────────────────────────────────────────────────────
    -- SECTION 7: Flags & Metrics
    -- ─────────────────────────────────────────────────────────────────────────

    is_overdue              BOOLEAN             NOT NULL DEFAULT FALSE               COMMENT 'TRUE = target_completion_date has passed and hazard is not yet closed. Updated by cron job.',
    is_recurring            BOOLEAN             NOT NULL DEFAULT FALSE               COMMENT 'TRUE = this hazard has occurred before. Flagged by HSE reviewer for trend analysis.',
    is_contractor_related   BOOLEAN             NOT NULL DEFAULT FALSE               COMMENT 'TRUE = a contractor was involved. Drives contractor performance KPIs.',
    is_employee_related     BOOLEAN             NOT NULL DEFAULT FALSE               COMMENT 'TRUE = a specific employee was involved or affected.',
    email_sent              BOOLEAN             NOT NULL DEFAULT FALSE               COMMENT 'TRUE = initial notification email has been dispatched to responsible person.',
    notification_sent       BOOLEAN             NOT NULL DEFAULT FALSE               COMMENT 'TRUE = in-app notification has been sent.',
    requires_rca            BOOLEAN             NOT NULL DEFAULT FALSE               COMMENT 'TRUE = Root Cause Analysis is required for this hazard (typically High/Extreme).',
    escalated               BOOLEAN             NOT NULL DEFAULT FALSE               COMMENT 'TRUE = hazard has been escalated to management due to risk level or overdue status.',
    days_open               SMALLINT UNSIGNED   NOT NULL DEFAULT 0                   COMMENT 'Computed field updated daily by cron. Number of days since date_reported. Used in dashboards.',

    -- ─────────────────────────────────────────────────────────────────────────
    -- SECTION 8: Audit Trail
    -- ─────────────────────────────────────────────────────────────────────────

    created_by              BIGINT UNSIGNED     NOT NULL                             COMMENT 'FK → users.user_id — system user who created this record.',
    updated_by              BIGINT UNSIGNED     NULL                                 COMMENT 'FK → users.user_id — system user who last modified this record.',
    created_at              DATETIME(3)         NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at              DATETIME(3)         NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at              DATETIME(3)         NULL                                 COMMENT 'Soft-delete. Hazards are NEVER hard-deleted. Regulatory compliance requirement.',

    -- ─────────────────────────────────────────────────────────────────────────
    -- CONSTRAINTS
    -- ─────────────────────────────────────────────────────────────────────────

    PRIMARY KEY (hazard_id),
    UNIQUE KEY uq_hazards_number (hazard_number)                                     COMMENT 'Hazard reference numbers must be globally unique.',

    CONSTRAINT chk_hazards_dates
        CHECK (actual_completion_date IS NULL OR actual_completion_date >= date_reported)
                                                                                     COMMENT 'Completion date cannot be before the report date.',

    CONSTRAINT chk_hazards_closure
        CHECK (closure_date IS NULL OR actual_completion_date IS NOT NULL)           COMMENT 'Cannot close a hazard without a completion date.',

    -- ─────────────────────────────────────────────────────────────────────────
    -- FOREIGN KEYS
    -- ─────────────────────────────────────────────────────────────────────────

    CONSTRAINT fk_hazards_plant
        FOREIGN KEY (plant_id)              REFERENCES plants             (plant_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_hazards_department
        FOREIGN KEY (department_id)         REFERENCES departments        (department_id)
        ON UPDATE CASCADE ON DELETE SET NULL,

    CONSTRAINT fk_hazards_location
        FOREIGN KEY (location_id)           REFERENCES locations          (location_id)
        ON UPDATE CASCADE ON DELETE SET NULL,

    CONSTRAINT fk_hazards_category
        FOREIGN KEY (category_id)           REFERENCES hazard_categories  (category_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_hazards_type
        FOREIGN KEY (hazard_type_id)        REFERENCES hazard_types       (hazard_type_id)
        ON UPDATE CASCADE ON DELETE SET NULL,

    CONSTRAINT fk_hazards_risk_rating
        FOREIGN KEY (risk_rating_id)        REFERENCES risk_ratings       (risk_rating_id)
        ON UPDATE CASCADE ON DELETE SET NULL,

    CONSTRAINT fk_hazards_revised_risk
        FOREIGN KEY (revised_risk_rating_id) REFERENCES risk_ratings      (risk_rating_id)
        ON UPDATE CASCADE ON DELETE SET NULL,

    CONSTRAINT fk_hazards_status
        FOREIGN KEY (status_id)             REFERENCES statuses           (status_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_hazards_reporter
        FOREIGN KEY (reported_by)           REFERENCES employees          (employee_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_hazards_responsible
        FOREIGN KEY (responsible_person_id) REFERENCES employees          (employee_id)
        ON UPDATE CASCADE ON DELETE SET NULL,

    CONSTRAINT fk_hazards_reviewer
        FOREIGN KEY (reviewer_id)           REFERENCES employees          (employee_id)
        ON UPDATE CASCADE ON DELETE SET NULL,

    CONSTRAINT fk_hazards_approver
        FOREIGN KEY (approver_id)           REFERENCES employees          (employee_id)
        ON UPDATE CASCADE ON DELETE SET NULL,

    CONSTRAINT fk_hazards_affected_emp
        FOREIGN KEY (affected_employee_id)  REFERENCES employees          (employee_id)
        ON UPDATE CASCADE ON DELETE SET NULL,

    CONSTRAINT fk_hazards_contractor
        FOREIGN KEY (contractor_id)         REFERENCES contractors        (contractor_id)
        ON UPDATE CASCADE ON DELETE SET NULL,

    CONSTRAINT fk_hazards_area_manager
        FOREIGN KEY (area_manager_id)       REFERENCES employees          (employee_id)
        ON UPDATE CASCADE ON DELETE SET NULL,

    CONSTRAINT fk_hazards_created_by
        FOREIGN KEY (created_by)            REFERENCES users              (user_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_hazards_updated_by
        FOREIGN KEY (updated_by)            REFERENCES users              (user_id)
        ON UPDATE CASCADE ON DELETE SET NULL,

    -- ─────────────────────────────────────────────────────────────────────────
    -- INDEXES — Designed for reporting dashboard query patterns
    -- ─────────────────────────────────────────────────────────────────────────

    -- Single-column lookups
    INDEX idx_hazards_plant_id              (plant_id)                               COMMENT 'Multi-plant filtering.',
    INDEX idx_hazards_department_id         (department_id)                          COMMENT 'Department KPI queries.',
    INDEX idx_hazards_location_id           (location_id)                            COMMENT 'Location-based analysis.',
    INDEX idx_hazards_status_id             (status_id)                              COMMENT 'Status filtering — most common UI filter.',
    INDEX idx_hazards_category_id           (category_id)                            COMMENT 'Category pie chart queries.',
    INDEX idx_hazards_risk_rating_id        (risk_rating_id)                         COMMENT 'Risk rating dashboard breakdown.',
    INDEX idx_hazards_reported_by           (reported_by)                            COMMENT 'My reported hazards view.',
    INDEX idx_hazards_responsible_person    (responsible_person_id)                  COMMENT 'My assigned hazards view.',
    INDEX idx_hazards_date_reported         (date_reported)                          COMMENT 'Date range filtering — most common date filter.',
    INDEX idx_hazards_is_overdue            (is_overdue)                             COMMENT 'Overdue hazard KPI card.',
    INDEX idx_hazards_deleted_at            (deleted_at)                             COMMENT 'Soft-delete filtering.',

    -- Composite indexes for dashboard queries
    INDEX idx_hazards_dept_date             (department_id, date_reported)           COMMENT 'Department hazard count by date.',
    INDEX idx_hazards_plant_status          (plant_id, status_id)                    COMMENT 'Plant-level status dashboard.',
    INDEX idx_hazards_plant_date            (plant_id, date_reported)                COMMENT 'Plant-level trend analysis.',
    INDEX idx_hazards_risk_date             (risk_rating_id, date_reported)          COMMENT 'Risk rating trend over time.',
    INDEX idx_hazards_status_overdue        (status_id, is_overdue)                  COMMENT 'Open + overdue KPI card.',
    INDEX idx_hazards_category_dept         (category_id, department_id)             COMMENT 'Category breakdown by department.',
    INDEX idx_hazards_contractor_related    (is_contractor_related, plant_id)        COMMENT 'Contractor hazard performance.',
    INDEX idx_hazards_target_date           (target_completion_date, is_overdue)     COMMENT 'Upcoming and overdue target dates.'

) ENGINE=InnoDB
  AUTO_INCREMENT=1
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='Core hazard management table. Hub of Phase 3 module. Supports complete lifecycle from Draft to Closure.';


-- =============================================================================
-- Seed Data — 3 sample hazard records
-- Demonstrates different lifecycle stages for testing.
-- All FKs must be resolved from previously seeded data.
-- =============================================================================

INSERT INTO hazards (
    hazard_number,      title,
    plant_id,           department_id,          location_id,
    category_id,        hazard_type_id,         risk_rating_id,     status_id,
    reported_by,        responsible_person_id,  reviewer_id,
    description,        observation,            immediate_action,
    date_reported,      time_reported,
    target_completion_date,
    is_employee_related,    email_sent,         notification_sent,
    created_by
)
VALUES
(
    'HAZ-2026-SKR-00001',
    'Exposed Electrical Wiring Near Boiler Room Entrance',
    'PLT-CBL-SKR-001',  'DEP-ENG-001',          'LOC-BOILER',
    1,                  2,                      2,                  2,
    'EMP-PROD-002',     'EMP-ENG-002',          'EMP-HSE-001',
    'Live electrical wiring observed exposed near the main entrance of the Boiler Room. Insulation has deteriorated and poses serious electrocution risk to any personnel entering the area.',
    'Two wires approximately 15cm long with no insulation, touching the metal door frame.',
    'Area cordoned off with caution tape. Electrical team notified immediately.',
    '2026-07-28',       '09:30:00',
    '2026-08-04',
    FALSE,              TRUE,                   TRUE,
    2
),
(
    'HAZ-2026-SKR-00002',
    'Oil Spill on Production Line 1 Floor',
    'PLT-CBL-SKR-001',  'DEP-PROD-001',         'LOC-PROD-L1',
    10,                 2,                      4,                  4,
    'EMP-PROD-003',     'EMP-PROD-001',         'EMP-HSE-002',
    'Lubricating oil observed leaking from packaging machine gearbox, creating a slip hazard across approximately 3 square meters of the production floor.',
    'Oil pooling under and around Packaging Machine #3. Workers walking through without awareness.',
    'Warning cones placed. Absorbent material applied. Machine isolated temporarily.',
    '2026-07-30',       '14:15:00',
    '2026-08-06',
    FALSE,              TRUE,                   TRUE,
    2
),
(
    'HAZ-2026-SKR-00003',
    'Fire Extinguisher Pressure Below Safe Level — Packing Area',
    'PLT-CBL-SKR-001',  'DEP-PROD-001',         'LOC-PACK',
    4,                  2,                      3,                  5,
    'EMP-HSE-002',      'EMP-ENG-001',          'EMP-HSE-001',
    'Monthly inspection revealed that 3 out of 8 fire extinguishers in the Packing Area show pressure gauge in the red zone, indicating they are depleted and non-functional.',
    'Pressure gauge needle pointing to red zone on extinguishers numbered P-04, P-06, and P-08.',
    'Flagged for immediate replacement. HSE team notified and maintenance request raised.',
    '2026-07-31',       '11:00:00',
    '2026-08-03',
    FALSE,              TRUE,                   TRUE,
    1
);


-- =============================================================================
-- Verification
-- =============================================================================

-- Summary of seeded hazards
SELECT
    h.hazard_number,
    h.title,
    hc.category_name,
    ht.type_name,
    rr.rating_name,
    s.status_name,
    h.date_reported,
    h.target_completion_date,
    h.is_overdue
FROM hazards h
JOIN hazard_categories  hc  ON h.category_id        = hc.category_id
LEFT JOIN hazard_types  ht  ON h.hazard_type_id      = ht.hazard_type_id
LEFT JOIN risk_ratings  rr  ON h.risk_rating_id      = rr.risk_rating_id
JOIN statuses           s   ON h.status_id           = s.status_id
ORDER BY h.hazard_id;

-- Dashboard KPI query — hazards by status
SELECT
    s.status_name,
    s.color,
    COUNT(h.hazard_id) AS total
FROM statuses s
LEFT JOIN hazards h ON h.status_id = s.status_id AND h.deleted_at IS NULL
WHERE s.module_name = 'hazards'
GROUP BY s.status_id, s.status_name, s.color
ORDER BY s.display_order;
