-- ==================================================
-- TABLE NAME
--   near_misses
--
-- Purpose
--   Enterprise near miss register for ISO 45001 proactive incident prevention,
--   OSHA-style reporting, SAP EHS workflow, and PowerApps-compatible capture.
--   The human-readable number is generated by MySQL as NM-YYYY-####.
--
-- Relationships
--   plants, departments, locations, employees, contractors, hazard_categories,
--   hazard_types, risk_ratings, statuses, hazards, and users.
--
-- Indexes
--   Unique generated number, plant/date, status/plant, risk/date, reporter/date,
--   investigation flag/status, linked hazard, and soft-delete filtering.
--
-- Workflow
--   Draft -> Submitted -> Under Investigation -> Closed.
--   Cancelled is terminal for duplicate or invalid submissions. Status changes
--   are recorded by 25_near_miss_status_history.sql.
--
-- Author
--   CBL HSE Database Architecture
--
-- Version
--   1.0.0 | Phase 4 | MySQL 8
-- ==================================================

USE cbl_hse;

CREATE TABLE IF NOT EXISTS near_misses (

    -- Identity
    near_miss_id           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT
                               COMMENT 'Surrogate primary key.',
    near_miss_number       VARCHAR(20) GENERATED ALWAYS AS (
                               CONCAT('NM-', YEAR(event_datetime), '-', LPAD(near_miss_id, 4, '0'))
                           ) STORED
                               COMMENT 'Generated enterprise reference, for example NM-2026-0001.',

    -- Event context
    event_datetime         DATETIME(3) NOT NULL
                               COMMENT 'Date and time at which the near miss occurred.',
    plant_id               CHAR(36) NOT NULL
                               COMMENT 'FK -> plants.plant_id.',
    department_id          CHAR(36) NULL
                               COMMENT 'FK -> departments.department_id.',
    location_id            CHAR(36) NULL
                               COMMENT 'FK -> locations.location_id.',
    shift_code             ENUM('day', 'evening', 'night', 'rotating', 'unknown')
                               NOT NULL DEFAULT 'unknown'
                               COMMENT 'Operational shift during the event.',

    -- People and involvement
    reported_by            CHAR(36) NOT NULL
                               COMMENT 'FK -> employees.employee_id; person reporting the event.',
    affected_employee_id   CHAR(36) NULL
                               COMMENT 'FK -> employees.employee_id; person exposed or potentially affected.',
    affected_designation   VARCHAR(150) NULL
                               COMMENT 'Designation snapshot at event time for historical reporting.',
    contractor_involved    BOOLEAN NOT NULL DEFAULT FALSE
                               COMMENT 'TRUE when a contractor was involved in or exposed to the event.',
    contractor_id          CHAR(36) NULL
                               COMMENT 'FK -> contractors.contractor_id; required when contractor_involved is TRUE.',

    -- Classification and narrative
    description            TEXT NOT NULL
                               COMMENT 'What happened, including the unsafe act or condition observed.',
    immediate_action_taken TEXT NULL
                               COMMENT 'Immediate containment or recovery action taken at the scene.',
    potential_consequence  TEXT NOT NULL
                               COMMENT 'Credible injury, illness, damage, or loss that could have occurred.',
    risk_rating_id         BIGINT UNSIGNED NOT NULL
                               COMMENT 'FK -> risk_ratings.risk_rating_id; assessed potential risk.',
    category_id             BIGINT UNSIGNED NOT NULL
                               COMMENT 'FK -> hazard_categories.category_id.',
    hazard_type_id          BIGINT UNSIGNED NULL
                               COMMENT 'FK -> hazard_types.hazard_type_id.',
    further_investigation_required BOOLEAN NOT NULL DEFAULT FALSE
                               COMMENT 'TRUE enables investigation and RCA workflow.',
    status_id              BIGINT UNSIGNED NOT NULL DEFAULT 13
                               COMMENT 'FK -> statuses.status_id; must belong to module near_misses.',
    remarks                TEXT NULL
                               COMMENT 'Additional HSE or management remarks.',
    linked_hazard_id       BIGINT UNSIGNED NULL
                               COMMENT 'FK -> hazards.hazard_id when the near miss is linked to a known hazard.',

    -- Audit and retention
    created_by             BIGINT UNSIGNED NOT NULL
                               COMMENT 'FK -> users.user_id; user who created the record.',
    updated_by             BIGINT UNSIGNED NOT NULL
                               COMMENT 'FK -> users.user_id; user who last updated the record.',
    created_at             DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at             DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
                               ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at             DATETIME(3) NULL
                               COMMENT 'Soft-delete timestamp; records must not be physically deleted.',

    PRIMARY KEY (near_miss_id),
    UNIQUE KEY uq_near_misses_number (near_miss_number),

    CONSTRAINT chk_near_misses_contractor
        CHECK (
            (contractor_involved = TRUE AND contractor_id IS NOT NULL)
            OR (contractor_involved = FALSE AND contractor_id IS NULL)
        ),
    CONSTRAINT fk_near_misses_plant
        FOREIGN KEY (plant_id) REFERENCES plants (plant_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_near_misses_department
        FOREIGN KEY (department_id) REFERENCES departments (department_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_near_misses_location
        FOREIGN KEY (location_id) REFERENCES locations (location_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_near_misses_reporter
        FOREIGN KEY (reported_by) REFERENCES employees (employee_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_near_misses_affected_employee
        FOREIGN KEY (affected_employee_id) REFERENCES employees (employee_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_near_misses_contractor
        FOREIGN KEY (contractor_id) REFERENCES contractors (contractor_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_near_misses_risk_rating
        FOREIGN KEY (risk_rating_id) REFERENCES risk_ratings (risk_rating_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_near_misses_category
        FOREIGN KEY (category_id) REFERENCES hazard_categories (category_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_near_misses_type
        FOREIGN KEY (hazard_type_id) REFERENCES hazard_types (hazard_type_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_near_misses_status
        FOREIGN KEY (status_id) REFERENCES statuses (status_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_near_misses_linked_hazard
        FOREIGN KEY (linked_hazard_id) REFERENCES hazards (hazard_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_near_misses_created_by
        FOREIGN KEY (created_by) REFERENCES users (user_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_near_misses_updated_by
        FOREIGN KEY (updated_by) REFERENCES users (user_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    INDEX idx_near_misses_plant_event (plant_id, event_datetime),
    INDEX idx_near_misses_status_plant (status_id, plant_id),
    INDEX idx_near_misses_risk_event (risk_rating_id, event_datetime),
    INDEX idx_near_misses_reporter_event (reported_by, event_datetime),
    INDEX idx_near_misses_investigation_status (further_investigation_required, status_id),
    INDEX idx_near_misses_linked_hazard (linked_hazard_id),
    INDEX idx_near_misses_deleted_at (deleted_at)

) ENGINE=InnoDB
  AUTO_INCREMENT=1
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='Enterprise near miss register with generated numbering, workflow state, classification, and audit ownership.';

-- ==================================================
-- Seed Data
-- ==================================================

INSERT INTO near_misses (
    event_datetime, plant_id, department_id, location_id, shift_code,
    reported_by, affected_employee_id, affected_designation,
    contractor_involved, contractor_id, description, immediate_action_taken,
    potential_consequence, risk_rating_id, category_id, hazard_type_id,
    further_investigation_required, status_id, remarks, linked_hazard_id,
    created_by, updated_by, created_at, updated_at
) VALUES
(
    '2026-07-28 09:20:00.000', 'PLT-CBL-SKR-001', 'DEP-PROD-001', 'LOC-PROD-L1', 'day',
    'EMP-PROD-003', 'EMP-PROD-003', 'Production Operator',
    FALSE, NULL,
    'A pallet jack entered the marked pedestrian route near the bagging line while an operator was crossing. No contact occurred and the pallet jack stopped before the crossing.',
    'Stopped the pallet jack, held the pedestrian crossing, and briefed both operators on route separation.',
    'A collision could have caused a serious crush injury or lost-time injury.',
    2, 12, 10, TRUE, 15,
    'Investigation requested because vehicle and pedestrian segregation was not effective during the shift.',
    NULL, 2, 2, '2026-07-28 09:25:00.000', '2026-07-28 09:25:00.000'
),
(
    '2026-07-30 14:10:00.000', 'PLT-CBL-SKR-001', 'DEP-ENG-001', 'LOC-ELEC', 'day',
    'EMP-ENG-002', NULL, NULL,
    FALSE, NULL,
    'A maintenance technician found the MCC panel door not fully latched during a routine walk-through. The panel was energized, but no one had accessed the exposed section.',
    'Restricted access, isolated the panel, and secured the latch before returning the area to service.',
    'Unintended access could have resulted in electric shock, arc flash, or serious burns.',
    2, 1, 11, FALSE, 14,
    'Panel latch inspection added to the next electrical preventive-maintenance round.',
    NULL, 3, 3, '2026-07-30 14:15:00.000', '2026-07-30 14:15:00.000'
),
(
    '2026-08-01 21:40:00.000', 'PLT-CBL-SKR-001', 'DEP-ENG-001', 'LOC-WORKSHOP', 'night',
    'EMP-ENG-002', NULL, NULL,
    TRUE, 'CON-005',
    'A contractor mechanic nearly slipped on a thin oil film beside the workshop lathe while carrying a tool case. The mechanic recovered without falling.',
    'Stopped the task, placed warning signage, cleaned the oil, and checked the surrounding floor for additional contamination.',
    'A fall could have caused a fracture, head injury, or contact with moving equipment.',
    3, 10, 7, TRUE, 13,
    'Contractor toolbox talk and housekeeping inspection scheduled before the next night shift.',
    NULL, 4, 4, '2026-08-01 21:45:00.000', '2026-08-01 21:45:00.000'
);

-- ==================================================
-- Verification
-- ==================================================

SELECT
    nm.near_miss_id,
    nm.near_miss_number,
    nm.event_datetime,
    nm.plant_id,
    s.status_name,
    rr.rating_name,
    nm.contractor_involved,
    nm.further_investigation_required
FROM near_misses nm
JOIN plants p ON p.plant_id = nm.plant_id
JOIN statuses s ON s.status_id = nm.status_id
JOIN risk_ratings rr ON rr.risk_rating_id = nm.risk_rating_id
WHERE nm.deleted_at IS NULL
ORDER BY nm.event_datetime;
